/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CareersRouteImport } from './routes/careers'
import { Route as CommunityRouteImport } from './routes/community'
import { Route as CoursesRouteImport } from './routes/courses'
import { Route as GuideRouteImport } from './routes/guide'
import { Route as PinboardRouteImport } from './routes/pinboard'
import { Route as QuizRouteImport } from './routes/quiz'
import { Route as VoicesRouteImport } from './routes/voices'
import { Route as CareersIndexRouteImport } from './routes/careers.index'
import { Route as CareersCareerIdRouteImport } from './routes/careers.$careerId'
import { Route as CoursesIndexRouteImport } from './routes/courses.index'
import { Route as CoursesCourseIdRouteImport } from './routes/courses.$courseId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersRoute = CareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityRoute = CommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesRoute = CoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => rootRouteImport,
} as any)
const GuideRoute = GuideRouteImport.update({
  id: '/guide',
  path: '/guide',
  getParentRoute: () => rootRouteImport,
} as any)
const PinboardRoute = PinboardRouteImport.update({
  id: '/pinboard',
  path: '/pinboard',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizRoute = QuizRouteImport.update({
  id: '/quiz',
  path: '/quiz',
  getParentRoute: () => rootRouteImport,
} as any)
const VoicesRoute = VoicesRouteImport.update({
  id: '/voices',
  path: '/voices',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersIndexRoute = CareersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CareersRoute,
} as any)
const CareersCareerIdRoute = CareersCareerIdRouteImport.update({
  id: '/$careerId',
  path: '/$careerId',
  getParentRoute: () => CareersRoute,
} as any)
const CoursesIndexRoute = CoursesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CoursesRoute,
} as any)
const CoursesCourseIdRoute = CoursesCourseIdRouteImport.update({
  id: '/$courseId',
  path: '/$courseId',
  getParentRoute: () => CoursesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/careers': typeof CareersRouteWithChildren
  '/community': typeof CommunityRoute
  '/courses': typeof CoursesRouteWithChildren
  '/guide': typeof GuideRoute
  '/pinboard': typeof PinboardRoute
  '/quiz': typeof QuizRoute
  '/voices': typeof VoicesRoute
  '/careers/$careerId': typeof CareersCareerIdRoute
  '/courses/$courseId': typeof CoursesCourseIdRoute
  '/careers/': typeof CareersIndexRoute
  '/courses/': typeof CoursesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/community': typeof CommunityRoute
  '/guide': typeof GuideRoute
  '/pinboard': typeof PinboardRoute
  '/quiz': typeof QuizRoute
  '/voices': typeof VoicesRoute
  '/careers/$careerId': typeof CareersCareerIdRoute
  '/courses/$courseId': typeof CoursesCourseIdRoute
  '/careers': typeof CareersIndexRoute
  '/courses': typeof CoursesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/careers': typeof CareersRouteWithChildren
  '/community': typeof CommunityRoute
  '/courses': typeof CoursesRouteWithChildren
  '/guide': typeof GuideRoute
  '/pinboard': typeof PinboardRoute
  '/quiz': typeof QuizRoute
  '/voices': typeof VoicesRoute
  '/careers/$careerId': typeof CareersCareerIdRoute
  '/courses/$courseId': typeof CoursesCourseIdRoute
  '/careers/': typeof CareersIndexRoute
  '/courses/': typeof CoursesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/careers'
    | '/community'
    | '/courses'
    | '/guide'
    | '/pinboard'
    | '/quiz'
    | '/voices'
    | '/careers/$careerId'
    | '/courses/$courseId'
    | '/careers/'
    | '/courses/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/community'
    | '/guide'
    | '/pinboard'
    | '/quiz'
    | '/voices'
    | '/careers/$careerId'
    | '/courses/$courseId'
    | '/careers'
    | '/courses'
  id:
    | '__root__'
    | '/'
    | '/careers'
    | '/community'
    | '/courses'
    | '/guide'
    | '/pinboard'
    | '/quiz'
    | '/voices'
    | '/careers/$careerId'
    | '/courses/$courseId'
    | '/careers/'
    | '/courses/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CareersRoute: typeof CareersRouteWithChildren
  CommunityRoute: typeof CommunityRoute
  CoursesRoute: typeof CoursesRouteWithChildren
  GuideRoute: typeof GuideRoute
  PinboardRoute: typeof PinboardRoute
  QuizRoute: typeof QuizRoute
  VoicesRoute: typeof VoicesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers': {
      id: '/careers'
      path: '/careers'
      fullPath: '/careers'
      preLoaderRoute: typeof CareersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community': {
      id: '/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof CommunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses': {
      id: '/courses'
      path: '/courses'
      fullPath: '/courses'
      preLoaderRoute: typeof CoursesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guide': {
      id: '/guide'
      path: '/guide'
      fullPath: '/guide'
      preLoaderRoute: typeof GuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pinboard': {
      id: '/pinboard'
      path: '/pinboard'
      fullPath: '/pinboard'
      preLoaderRoute: typeof PinboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz': {
      id: '/quiz'
      path: '/quiz'
      fullPath: '/quiz'
      preLoaderRoute: typeof QuizRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/voices': {
      id: '/voices'
      path: '/voices'
      fullPath: '/voices'
      preLoaderRoute: typeof VoicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers/': {
      id: '/careers/'
      path: '/'
      fullPath: '/careers/'
      preLoaderRoute: typeof CareersIndexRouteImport
      parentRoute: typeof CareersRoute
    }
    '/careers/$careerId': {
      id: '/careers/$careerId'
      path: '/$careerId'
      fullPath: '/careers/$careerId'
      preLoaderRoute: typeof CareersCareerIdRouteImport
      parentRoute: typeof CareersRoute
    }
    '/courses/': {
      id: '/courses/'
      path: '/'
      fullPath: '/courses/'
      preLoaderRoute: typeof CoursesIndexRouteImport
      parentRoute: typeof CoursesRoute
    }
    '/courses/$courseId': {
      id: '/courses/$courseId'
      path: '/$courseId'
      fullPath: '/courses/$courseId'
      preLoaderRoute: typeof CoursesCourseIdRouteImport
      parentRoute: typeof CoursesRoute
    }
  }
}

interface CareersRouteChildren {
  CareersCareerIdRoute: typeof CareersCareerIdRoute
  CareersIndexRoute: typeof CareersIndexRoute
}

const CareersRouteChildren: CareersRouteChildren = {
  CareersCareerIdRoute: CareersCareerIdRoute,
  CareersIndexRoute: CareersIndexRoute,
}

const CareersRouteWithChildren =
  CareersRoute._addFileChildren(CareersRouteChildren)

interface CoursesRouteChildren {
  CoursesCourseIdRoute: typeof CoursesCourseIdRoute
  CoursesIndexRoute: typeof CoursesIndexRoute
}

const CoursesRouteChildren: CoursesRouteChildren = {
  CoursesCourseIdRoute: CoursesCourseIdRoute,
  CoursesIndexRoute: CoursesIndexRoute,
}

const CoursesRouteWithChildren =
  CoursesRoute._addFileChildren(CoursesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CareersRoute: CareersRouteWithChildren,
  CommunityRoute: CommunityRoute,
  CoursesRoute: CoursesRouteWithChildren,
  GuideRoute: GuideRoute,
  PinboardRoute: PinboardRoute,
  QuizRoute: QuizRoute,
  VoicesRoute: VoicesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
